### ISSUE TITLE
Pair down logging systems

### ISSUE THREAD

**Issue by TTWNO** [odilia-app/odilia#13]
Currently two logging systems are used across the various binaries and libraries for the project.

`sohkd` and `sohks` use the log crate, and the rest of Odilia is using `tracing`. Pick one and make the rest conform. I'm happy with either as they seem to work nearly the same, but I don't know enough about what matters to make a choice. They both work around the same for me.

**Comment by albertotirla** [comment]
the short of it is, tracing is more advanced than log, because it works with async and supports structured logging, so I think tracing should be used in both cases. Since the tracing stack can't be shared across binaries very easily the way we have things set up now, I recommend we move the logging subsystem initialisation functions to the common crate, where all binaries, present and future, could make use of them. This means we have duplicated dependencies across the workspace at large, but I see no way around it, so that's the most viable solution I could think of.

**Comment by mcb2003** [comment]
We actually use [`tracing-log`](https://crates.io/crates/tracing-log) in the main Odilia binary to convert all `log` messages to `tracing` messages so they're filtered and output in the same way. This is because some crates we depend on use `log`, while others (namely Tokio, as they made it), use `tracing`. So as it stands, converting sohkd to use `tracing` won't actually change our dependency graph

We have to ask ourselves how important seeing the messages from the crates that use `log` is. If it isn't, we can remove `tracing-log`, but we still won't be able to remove `log` itself, unless those crates have a feature to disable it. Most don't, because the `log` crate is very small and almost free to use when there's no logger:

> If no logging implementation is selected, the facade falls back to a “noop” implementation that ignores all log messages. The overhead in this case is very small - just an integer load, comparison and jump.

**Comment by mcb2003** [comment]
It turns out that [`log` now has experimental structured logging too](https://docs.rs/log/latest/log/#structured-logging). Unfortunately, the syntax isn't compatible with `tracing`:

```rust
info!(target: "yak_events", yak = as_serde!(yak); "Commencing yak shaving");
```

I could be wrong but I don't think there's going to be a solution where we end up using only one of these libraries. We can decide which subscriber to use, whether to bridge the two together, and we can integrate them with crates like [`eyre`](https://crates.io/crates/eyre) as we currently do, but I don't think we can get rid of either of them. If we want to remove logging dependencies, the main candidates to remove are:

* [`tracing-error`](https://crates.io/crates/tracing-error)
* [`color-eyre`](https://crates.io/crates/color-eyre)
* [`eyre`](https://crates.io/crates/eyre) -- we could use [`anyhow`](ghttps://crates.io/crates/anyhow) instead, which may reduce dependencies

**Comment by mcb2003** [comment]
Here's the [Matrix thread about this issue](https://matrix.to/#/!BVPeWFRhpOwtjxKvET:matrix.org/$eE80QJvFWoCWUCplTSwIYnQvOteE0Xf3Ac5H2bN7MJ8?via=matrix.org&via=t2bot.io&via=lowerelements.club)
