### ISSUE TITLE
Read line of text on up/down arrow instead of entire paragraph.

### ISSUE THREAD

**Issue by TTWNO** [odilia-app/odilia#5]
Through looking into [Orca's source code](https://gitlab.gnome.org/GNOME/orca) @albertotirla has discovered that Orca is able to do line by line navigation by interrupting the caret moving functionality and handling the moving of the caret itself. If I remember correctly, that's what he said.

Anywho, I would like to avoid this method, and propose a similar, less intrusive method:

1. When an arrow (or ctrl+arrow, or Home/End) is pressed in focus mode, notify the screen reader event loop.
2. When the next text-caret-moved event is triggered, decide based on if it was left/right or up/down whether to speak the line or the character, or the word.

I think this method is somewhat cleaner as it allows the user to navigate as they would normally, with no over-brearingness from the screen reader.

Also, despite our code being nearly fully asynchronous, I have little concern about the caret-moved event being received before the character is saved into our loop somehow. Remember that since Odilia current handles keys *before* they are sent to the a11y layer, or even the DE/WM itself, it is more-or-less impossible for Odilia to be awaiting something for so long that this event does not get processed in order.

**Comment by albertotirla** [comment]
yes, that's basically what I would suggest as well, however I have mixed feelings about it
On one hand, it would allow the screenreader to read what it should, regardless of how the caret chooses to move. This is very helpful on the web, where it seemns up and down arrows don't actually generate a caret move, unless it reaches another paragraph, or at least that's what happens in firefox. Also, if we get to support touchscreens, controllers, switches and other input methods, most likely the caret won't be moved by the system, so we would have to find a way to move by word, character and so on, while making the system put the carret where we think it should be, as long as we find a way to actually manipulate the caret of an accessible through the dbus api we're exposed to. This is basically what android is doing, with its navigation model which is based on granularity. Another idea around this concept is to make a different virtual cursor, which is always active and it's set to follow the focus. However, when caret issues on the web and maybe other things in the future happen, the cursor would detach from the system focus, being able to wonder around, in this case, each line of a paragraph, something similar to the jaws or voiceover cursor. That would basically be object nav, but more powerful since it would allow the user to zoom in on every detail of an accessible, including its text, description, etc.
On the other hand, I don't think orca can move the caret on its own, so it's very likely it does what you proposed above, first registers what key was pressed, then waits for carret moved, then it acts on the information. However, while this would be a good idea in the short term, I think the system should best handle its caret, as it happens in text boxes(both web and native), terminals, etc. Perhaps this scheme should only be applied if somewhere in the accessible hierarchy there is something with the role of web document, therefore we know that part represents an issue so we handle it in a certain way? ideas welcome here, this is not an easy problem to solve, since because the system was designed around orca and orca around the system, we have to do things the way orca does if we want to fit in, whatever else we do seemns to not work as we want and that's why we have to come up with apparently better designs that end up being some kind of hacks or another anyway.

**Comment by TTWNO** [comment]
You do make a good point about granularity. This could be useful, actually.

Thoughts on adding granularity as a state item? Then the user can decude how they want to move around the page without the need for home/end, Ctrl+left/Ctrl+right, etc.

Peraonally, I would prefer, generally speaking, for my caret to work as is unless there is some good reason not to.

But having a granulariry setting for Odilia and easily allowing the implementation of touch screen, well that's nice.

Thoughts? @mcb2003

**Comment by mcb2003** [comment]
All looks good to me :+1:. Discussion of granularity (similar to the VoiceOver roter as I described it) is [here on Matrix](https://matrix.to/#/!BVPeWFRhpOwtjxKvET:matrix.org/$p4QR_V-BNRMJWSP3w96n3wsrpPl38Zh0SWzXOwEg-ww?via=matrix.org&via=t2bot.io&via=lowerelements.club). I also think this would be a nice feature, but I wouldn't be surprised if Orca handling the caret itself is one of the reasons it can be so laggy sometimes, so I think this should be customizable. In the short-term though, I think we should implement @TTWNO's solution.

**Comment by TTWNO** [comment]
I messed around trying to get more natural flow to work for this, but found nothing consistent. The granularity will be set manually by the user, and I'll create a new issue for how to handle it more naturally.

**Comment by TTWNO** [comment]
Ok, the new solution is to change reading modes (state setting) when tab or up/down arrow are pressed. The key will not be grabbed, but rather passed through to the rest of the stack. Odilia will only be made aware of it by the passing of an event changing the reading mode of the screenreader.

* `tab` will cause Odilia to read entire elements of the page, document or application.
* `up/down` will cause Odilia to read line-by-line using the caret position to determine which line to read.

This is the next thing I'm looking at fixing.

**Comment by TTWNO** [comment]
Odilia now has a setting for text granularity which is set by using your arrow keys. The keys are not consumed, but will simply notify Odilia that the way you are reading text has changed.

As of now:

* `left` and `right` will change to `TextGranularity::Char`
* `up` and `down` will change to `TextGranularity::Line`
* `ctrl + left` and `ctrl + right` will change to `TextGranularity::Word`

This will also be reflected in the documentation on the website.

**Comment by TTWNO** [comment]
As of right now, this does not affect how the speech works, it only records it for a future function to deal with, but that in and of itself is half the battle.

**Comment by TTWNO** [comment]
Done! Yee-haw folks!
